openapi: "3.0.2"

info:
  title: Axum-CRUD-API
  version: 0.1.0
  description: "Simple API in Rust using Axum."

servers:
  - url: http://127.0.0.1:3000
    description: local

paths:
  /create:
    post:
      summary: creates a new certificate
      operationId: createCertificate
      description: Creates a new certificate in the list.
      tags:
        - create
      responses:
        "201":
          description: Returns the new certificate.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/certificate"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/certificate"
        description: Certificate details

  /read:
    get:
      summary: reads all certificates
      operationId: readAllCertificates
      description: Allows you to view all the certificates.
      tags:
        - read
      responses:
        "200":
          description: Returns all the certificates.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/certificate"

  /read/{id}:
    get:
      summary: reads one certificate
      operationId: readOneCertificate
      description: By passing a valid ID, you can view the corresponding certificate.
      tags:
        - read
      responses:
        "200":
          description: Returns one certificate.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/certificate"
      parameters:
        - name: id
          description: certificate id
          in: path
          required: true
          schema:
            type: integer

  /update/{id}:
    put:
      summary: updates a certificate
      operationId: updateCertificate
      description: Updates an existing certificate in the list.
      tags:
        - update
      responses:
        "200":
          description: Returns the updated certificate.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/certificate"
      parameters:
        - name: id
          description: Certificate id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/certificate"
        description: Certificate details

  /delete/{id}:
    delete:
      summary: deletes a certificate
      operationId: deleteCertificate
      description: Deletes an existing certificate in the list.
      tags:
        - delete
      responses:
        "200":
          description: Returns the deleted certificate.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/certificate"
      parameters:
        - name: id
          description: Certificate id
          in: path
          required: true
          schema:
            type: integer

components:
  schemas:
    certificate:
      type: object
      required:
        - id
        - name
        - course
        - grade
        - date
      properties:
        id:
          type: integer
          example: 72
        name:
          type: string
          example: Langley
        course:
          type: string
          example: MBCC
        status:
          type: boolean
          example: true
        date:
          type: string
          format: date
          example: "21-12-2022"
